@echo off
echo Emulator cihazini baslatin ve uygulamayi acin...
echo Kamera iznini verin ve crash olmasini bekleyin...
echo.
echo Crash loglarini yakaliyorum...
adb logcat -c
adb logcat *:E | findstr "ziraai"
